name: Build Stream Analytics

on:
  workflow_dispatch

jobs:
  build:
    name: Build ASA
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Force install azure-streamanalytics-cicd
      run: npm install -g -f azure-streamanalytics-cicd

    - name: test list files in bin directory
      run: |
        npm list -g azure-streamanalytics-cicd --depth=0

    - name: test list files in bin directory
      run: |
        cd /opt/hostedtoolcache/node/22.15.0/x64/lib
        ls -ltr
