name: Test Bicep Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-bicep:
    runs-on: ubuntu-24.04  # Use the latest Ubuntu 24 runner (adjust to 'ubuntu-latest' if 24 is not available)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Bicep CLI
      run: |
        # Install dependencies and Bicep CLI
        # curl -sL https://aka.ms/install-bicep.sh | sudo bash
        
        # Check the installation
        bicep --version




