name: Check AppArmor Status on Ubuntu Runners

on:
  workflow_dispatch:

jobs:
  check-apparmor:
    runs-on: ${{ matrix.ubuntu-image }}
    strategy:
      matrix:
        ubuntu-image: 
          - ubuntu-20.04-canary
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check AppArmor service status
        run: |
          echo "Checking AppArmor status on ${{ matrix.ubuntu-image }}..."
          # Check if apparmor is installed and if it's running
          if systemctl is-active --quiet apparmor; then
            echo "AppArmor is enabled"
          else
            echo "AppArmor is disabled"
          fi
