name: Debug
on:
  workflow_dispatch:

jobs:
  not_working:
    runs-on: ubuntu-latest
 #   container:
 #     image: python:3.10-slim
    steps:
      - name: python version
        run: python --version
        
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python
