name: Install ORAS on Ubuntu 24.04

on:
  workflow_dispatch:

jobs:
  install-oras:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ORAS CLI
        run: |
          ORAS_VERSION=$(curl -s https://api.github.com/repos/oras-project/oras/releases/latest | grep tag_name | cut -d '"' -f 4)
          curl -LO https://github.com/oras-project/oras/releases/download/${ORAS_VERSION}/oras_${ORAS_VERSION#v}_linux_amd64.tar.gz
          tar -xvf oras_${ORAS_VERSION#v}_linux_amd64.tar.gz oras
          sudo mv oras /usr/local/bin/oras
          oras version

      - name: Verify ORAS Installation
        run: oras version
