name: Test getent ahosts ipv6

on:
  workflow_dispatch:

jobs:
  test-getent:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]

    steps:
    - name: Run getent ahosts ipv6
      run: |
        echo "Testing on ${{ matrix.os }}"
        getent ahosts ::
