name: Testing kusto cli

on: workflow_dispatch
jobs:
  sudo:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - run: |
        dpkg -l | grep libicu
        curl -L "https://www.nuget.org/api/v2/package/Microsoft.Azure.Kusto.Tools/12.2.8" > kustocli.zip
        unzip kustocli.zip
        export KUSTO_CLI_PATH=$(find "$PWD" -name Kusto.Cli.dll | grep -m 1 netcore)
        echo $KUSTO_CLI_PATH
        dotnet $KUSTO_CLI_PATH "https://help.kusto.windows.net/Samples;Fed=true"
