name: Install libicu and Test

on:
  workflow_dispatch:

jobs:
  install-libicu:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update apt and install libicu
      run: |
        sudo apt-get update
        sudo apt-get install -y libicu-dev
        
    - name: Verify libicu installation
      run: |
        icu-config --version || echo "icu-config command not found, but libicu is installed."
        
    - name: Run your script or build
      run: |
        # Add the commands to run your script or application that depends on libicu
        echo "Running build or tests that require libicu..."
