name: "Test libicu latest"

on:
  workflow_dispatch:
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

 #   - name: Restore
 #     run: dotnet restore

    - name: Test
      run: dotnet --version

    - name: Execute few comms
      run: | 
          curl -v -O -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
          tar xzf ./actions-runner-linux-x64-2.317.0.tar.gz
          RUNNER_TOKEN="Redacted"
          ./config.sh --unattended --url https://github.com/subir0071/hello-world --token $RUNNER_TOKEN --replace
