name: Setup with ICU on Ubuntu 24

on: 
  workflow_dispatch:

jobs:
  setup-icu:
    runs-on: ubuntu-24.04 # The runner on which this will run

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update and install ICU
        run: |
          sudo apt update
          sudo apt install -y libicu-dev

      - name: Verify ICU installation
        run: |
          icu-config --version

      - name: Run your build steps
        run: |
          # Add your build steps here
          echo "Building your project..."

