name: Setup with ICU on Ubuntu 24

on: 
  push:
    branches:
      - main

jobs:
  setup-icu:
    runs-on: ubuntu-24.04 # The runner on which this will run

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify ICU installation
        run: |
          icu-config --version

      - name: Run your build steps
        run: |
          # Add your build steps here
          echo "Building your project..."

