name: Install ICU Globalization and Dependencies

on:
  workflow_dispatch:

jobs:
  install-icu:
    runs-on: ubuntu-latest  # GitHub-hosted runner for Linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Optional: Checkout your code if needed

    - name: Set DOTNET_SYSTEM_GLOBALIZATION_INVARIANT to 0
      run: echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0" >> $GITHUB_ENV  # Set environment variable

    - name: Install ICU Globalization Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libicu-dev

    - name: Verify libicu installation
      run: icu-config --version  # Verify that ICU is installed and available
