name: Testing ripgrep in gha 

on: workflow_dispatch
jobs:
  testing-ripgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Install latest ripgrep in gha
        run: |
          sudo apt update
          wget https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz
          tar -xvf ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz
          sudo mv ripgrep-14.1.1-x86_64-unknown-linux-musl/rg /usr/local/bin
      - name: Run ripgrep on stdinput
        run: echo "Hello, world!" | rg "Hello"
      - name: create a file with a message
        run: echo "Hello, world!" > hello.txt
      - name: Run ripgrep on a file
        run: rg "Hello" hello.txt  
      - name: Check for FIFOs stdin
        run: |
          lsof -p $$ | grep FIFO || echo "stdin is not a FIFO"
      - name: Run ripgrep without specifying a file (will fail, so debug)
        run: |
          sudo rg --debug "Hello" ./
