name: Podman info
on: 
  workflow_dispatch:
jobs:
  show:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    steps:
      - run: podman system info
