name: Test pwritev2 behavior - corrected

on:
  workflow_dispatch:

jobs:
  test-pwritev2:
    runs-on: ubuntu-24.04

    steps:
      - name: Create test program
        run: |
          cat > test_pwritev2.c << 'EOF'
          #define _GNU_SOURCE
          #include <fcntl.h>
          #include <stdio.h>
          #include <string.h>
          #include <unistd.h>
          #include <sys/syscall.h>
          #include <sys/uio.h>
          #include <errno.h>

          #ifndef RWF_NOAPPEND
          #define RWF_NOAPPEND 0x00000010
          #endif

          void print_file(const char *filename) {
              char buffer[100] = {0};
              int fd = open(filename, O_RDONLY);
              if (fd < 0) {
                  perror("open for read");
                  return;
              }
              read(fd, buffer, sizeof(buffer) - 1);
              close(fd);
              printf("File contents: [%s]\n", buffer);
          }

          int main() {
              const char *filename = "testfile.txt";
              struct iovec iov = { .iov_base = "   ", .iov_len = 3 };
              ssize_t ret;

             
              int fd = open(filename, O_CREAT | O_WRONLY | O_TRUNC, 0644);
              if (fd < 0) return perror("initial open"), 1;
              write(fd, "it's not working!", 18);
              close(fd);

              printf("Initial content:\n");
              print_file(filename);

              
              fd = open(filename, O_WRONLY | O_APPEND);
              if (fd < 0) return perror("open with O_APPEND"), 1;
              ret = syscall(SYS_pwritev2, fd, &iov, 1, 5, RWF_NOAPPEND);
              close(fd);
              printf("\nAfter pwritev2 with O_APPEND + RWF_NOAPPEND:\n");
              printf("pwritev2 returned: %zd\n", ret);
              print_file(filename);

              
              fd = open(filename, O_WRONLY);
              if (fd < 0) return perror("open without O_APPEND"), 1;
              ret = syscall(SYS_pwritev2, fd, &iov, 1, 5, 0);
              close(fd);
              printf("\nAfter pwritev2 without O_APPEND:\n");
              printf("pwritev2 returned: %zd\n", ret);
              print_file(filename);

              return 0;
          }
          EOF

      - name: Compile test_pwritev2.c
        run: gcc -o test_pwritev2 test_pwritev2.c

      - name: Run test
        run: ./test_pwritev2
