name: Ansible Lint Workflow

on:
  workflow_dispatch:

jobs:
  ansible-lint:
    name: Run Ansible Lint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]  # OS versions
        python-version: [3.11, 3.12, 3.13]  # Python versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ansible-lint
        run: |
          pip install ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint .
