name: Check Service Fabric Host Version

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  check-version:
    runs-on: windows-2022

    steps:
    - name: Check for Service Fabric version
      shell: pwsh
      run: |
        # Path to the fabrichost.exe (usually located in the Service Fabric installation directory)
        $fabrichostPath = "C:\Program Files\Microsoft Service Fabric\bin\abrichost.exe"
        
        # Check if fabrichost.exe exists
        if (Test-Path $fabrichostPath) {
            # Get version of fabrichost.exe using PowerShell
            $fileVersion = (Get-Item $fabrichostPath).VersionInfo.FileVersion
            Write-Host "fabrichost.exe version: $fileVersion"
        } else {
            Write-Host "fabrichost.exe not found at the expected location."
        }
