name: test ssh windows 2025

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2025
    steps:
    #   - name: enable inheritance
    #     shell: pwsh
    #     run: |
    #       icacls C:\ /inheritance:e /c /q 2>&1
      - uses: actions/checkout@v4
        with:
          ssh-key: "${{ secrets.TMP_SSH_KEY }}"
