name: Simple Windows Workflow

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019  # Windows environment

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: test simple command
        run: echo "Windows 2019 runner still working"
