name: Workspace Variable Value
on:
  workflow_dispatch:

jobs:
  checking_echo:
    runs-on: windows-2022

    steps:
      - name: test echo
        shell: pwsh
        run: |
          echo "Github Workspace value: %GITHUB_WORKSPACE%"
