name: A windows sdk
on:
  workflow_dispatch:
jobs:
  list-windows-sdks:
    runs-on: windows-2022
    steps:
      - name: List Windows SDK versions
        shell: pwsh
        run: |
          $sdkBasePath = "C:\Program Files (x86)\Windows Kits\10\Lib"

          if (Test-Path $sdkBasePath) {
            Write-Host "📦 Windows SDKs found in: $sdkBasePath"
            Get-ChildItem -Path $sdkBasePath -Directory | ForEach-Object {
              Write-Host "✅ Found Windows SDK version: $($_.Name)"
            }
          } else {
            Write-Error "❌ Windows SDK base path not found: $sdkBasePath"
          }

      - name: Check SDK MSI Build Version
        shell: pwsh
        run: |
          $sdk = Get-ItemProperty "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*" |
            Where-Object { $_.DisplayName -like "*Windows Software Development Kit*" } |
            Sort-Object DisplayVersion -Descending |
            Select-Object -First 1

          if ($sdk.DisplayVersion -eq "10.1.26100.3916") {
            Write-Host "✅ Required SDK version 10.1.26100.3916 is installed."
          } else {
            Write-Error "❌ Required SDK version not found. Found version: $($sdk.DisplayVersion)"
            exit 1
          }
