name: Print GITHUB_WORKSPACE on Windows

on:
  workflow_dispatch:

jobs:
  print-workspace:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print GITHUB_WORKSPACE
        run: echo "GITHUB_WORKSPACE=%GITHUB_WORKSPACE%"
        shell: cmd
