name: Install wingetcreate from GitHub Releases

on:
  workflow_dispatch:

jobs:
  install-wingetcreate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019]

    # steps:
    #   - name: Checkout repository
    #     uses: actions/checkout@v4

    #   - name: install dotnet 6.0.13
    #     uses: actions/setup-dotnet@v4
    #     with:
    #       dotnet-version: '6.x'
      
    

      - name: Download wingetcreate.exe
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe

          

      - name: Verify wingetcreate version
        run: |
          .\wingetcreate.exe --help
