name: Install wingetcreate from GitHub Releases

on:
  workflow_dispatch:

jobs:
  install-wingetcreate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install dotnet 6.0.13
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'
      
    

      - name: Download wingetcreate.exe
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
      - name: list files in RUNNER_TEMP
        run: |
          cd "$env:RUNNER_TEMP"
          dir

      - name: Check if wingetcreate.exe exists
        run: |
          if (-Not (Test-Path "$env:RUNNER_TEMP\wingetcreate.exe")) {
            Write-Error "wingetcreate.exe not found!"
            exit 1
          }

      - name: Verify wingetcreate version
        run: |
           & "$env:RUNNER_TEMP\wingetcreate.exe" --help
