name: Install wingetcreate from GitHub Releases

on:
  workflow_dispatch:

jobs:
  install-wingetcreate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest wingetcreate.exe release info
        id: get_release
        run: |
          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/microsoft/winget-create/releases/latest"
          $asset = $response.assets | Where-Object { $_.name -eq "wingetcreate.exe" }
          echo "WINGETCREATE_URL=$($asset.browser_download_url)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Download wingetcreate.exe
        run: |
          $exePath = "$env:RUNNER_TEMP\wingetcreate.exe"
          Invoke-WebRequest -Uri "$env:WINGETCREATE_URL" -OutFile $exePath
          echo "$env:RUNNER_TEMP" | Out-File -Append $env:GITHUB_PATH

      - name: list files in RUNNER_TEMP
        run: |
          cd "$env:RUNNER_TEMP"
          dir

      - name: Check if wingetcreate.exe exists
        run: |
          if (-Not (Test-Path "$env:RUNNER_TEMP\wingetcreate.exe")) {
            Write-Error "wingetcreate.exe not found!"
            exit 1
          }

      - name: Verify wingetcreate version
        run: |
          wingetcreate.exe help
