name: Install winget-create on all Windows runners

on:
  workflow_dispatch:

jobs:
  install-winget-create:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
          - windows-2022
          - windows-2025

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install winget-create
      shell: pwsh
      run: |
        choco install wingetcreate -y

    - name: Verify winget-create installation
      run: wingetcreate --version
